# Yarn Berry (v2+) 配置文件示例

# 使用 node_modules 链接器（传统模式）
nodeLinker: node-modules

# 或者使用 Plug'n'Play 模式（推荐，无 node_modules）
# nodeLinker: pnp

# 包管理器元数据
# enableGlobalCache: true

# npm 镜像源
# npmRegistryServer: "https://registry.npmmirror.com"

